version: '3'

services:
  redis:
    image: redis:latest
    restart: unless-stopped

  flask_app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - db-data:/data
    depends_on:
      - redis
      - sqlite_db
    restart: unless-stopped
    environment:
      - FLASK_ENV=production

  celery:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - db-data:/data
    container_name: cel01
    command: celery -A app.celery worker -l info
    links:
      - redis
    restart: unless-stopped
    environment:
      - FLASK_ENV=production

  sqlite_db:
    build: ./db
    volumes:
      - db-data:/data
    restart: unless-stopped

volumes:
  db-data: