version: '3'

services:
  redis:
    image: redis:latest
    restart: unless-stopped

  flask_app:
    build: 
      context: ./
      dockerfile: Dockerfile.production
    ports:
      - "8000:8000"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - db-data:/data
    depends_on:
      - redis
      - sqlite_db
    restart: unless-stopped

  celery:
    build: 
      context: ./
      dockerfile: Dockerfile.production
    volumes:
      - .:/src
      - db-data:/data
    container_name: cel01
    command: celery -A app.celery worker -l info
    links:
      - redis
    restart: unless-stopped

  sqlite_db:
    build: ./db
    volumes:
      - db-data:/data
    restart: unless-stopped

  proxy:
    build: ./proxy
    ports:
      - "80:80"
      - "443:443"
    links:
      - flask_app
    depends_on:
      - flask_app
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    restart: unless-stopped

volumes:
  db-data: