version: '3'

services:
  redis:
    image: redis:latest

  flask_app:
    image: armymarkdown:latest
    ports:
      - "443:8443"
      - "80:8000"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - redis

  celery:
    image: armymarkdown:latest
    volumes:
      - .:/src
    container_name: cel01
    command: celery -A app.celery worker -l info
    links:
      - redis