version: '3'

services:
  redis:
    image: redis:latest

  flask_app:
    build:
      context: ./
      dockerfile: Dockerfile.development
    ports:
      - "8000:8000"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - db-data:/data
    depends_on:
      - redis
      - sqlite_db

  celery:
    build: ./
    volumes:
      - .:/src
      - db-data:/data
    container_name: cel01
    command: celery -A app.celery worker -l info
    links:
      - redis

  sqlite_db:
    build: ./db
    volumes:
      - db-data:/data

volumes:
  db-data:
