version: '3'

services:
  redis:
    image: redis:latest
    networks:
      - army_net

  flask_app:
    build:
      context: ./
      dockerfile: Dockerfile.development
    ports:
      - 8000:8000
    volumes:
      - .:/app  # Mount current directory to /app in container
      - /etc/letsencrypt:/etc/letsencrypt
      - db-data:/data
    environment:
      - FLASK_SECRET=${FLASK_SECRET:-dev-secret-key-change-in-production}
      - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DEVELOPMENT=1
    depends_on:
      - redis
      - sqlite_db
    networks:
      - army_net


  celery:
    build:
      context: ./
      dockerfile: Dockerfile.development
    volumes:
      - .:/app  # Mount current directory to /app in container
      - db-data:/data
    container_name: cel01
    command: celery -A app.celery worker -l info
    environment:
      - FLASK_SECRET=${FLASK_SECRET:-dev-secret-key-change-in-production}
      - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DEVELOPMENT=1
    links:
      - redis
    networks:
      - army_net

  sqlite_db:
    build: ./db
    volumes:
      - db-data:/data
    networks:
      - army_net

  proxy:
    build: ./proxy
    ports:
      - 80:80
    links:
      - flask_app
    depends_on:
      - flask_app
    networks:
      - army_net

volumes:
  db-data:

networks:
  army_net:
