version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  flask_app:
    image: armymarkdown:latest
    ports:
      - "80:8000"
    depends_on:
      - redis

  celery:
    image: armymarkdown:latest
    volumes:
      - .:/src
    container_name: cel01
    command: celery -A app.celery worker -l info
    links:
      - redis
