name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.11

    - name: Create virtual environment and install dependencies
      run: |
        uv sync --all-extras

    - name: Set up test environment
      run: |
        export FLASK_SECRET="test-secret-key-for-ci"
        export REDIS_URL="redis://localhost:6379/15"
        export RECAPTCHA_PUBLIC_KEY="test-public-key"
        export RECAPTCHA_PRIVATE_KEY="test-private-key"
        export AWS_ACCESS_KEY_ID="test-access-key"
        export AWS_SECRET_ACCESS_KEY="test-secret-key"
        export DISABLE_CAPTCHA="true"
        export DEVELOPMENT="true"

    - name: Run code quality checks
      run: |
        uv run ruff check . --output-format=github
        uv run ruff format --check .


    - name: Run security checks
      run: |
        uv run bandit -r app.py armymarkdown/ db/ login.py forms.py clear-redis.py monitor-celery.py -f json || true
        uv run safety check || true

    - name: Run unit tests with coverage
      env:
        PYTHONPATH: .
        FLASK_SECRET: "test-secret-key-for-ci"
        REDIS_URL: "redis://localhost:6379/15"
        RECAPTCHA_PUBLIC_KEY: "test-public-key"
        RECAPTCHA_PRIVATE_KEY: "test-private-key"
        AWS_ACCESS_KEY_ID: "test-access-key"
        AWS_SECRET_ACCESS_KEY: "test-secret-key"
        DISABLE_CAPTCHA: "true"
        DEVELOPMENT: "true"
      run: |
        uv run pytest tests/ -m "not selenium" --cov=. --cov-report=xml --cov-report=html --cov-report=term-missing --continue-on-collection-errors --forked --tb=short --maxfail=10 -v || true

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Generate coverage badge
      run: |
        uv run coverage-badge -o coverage.svg || true

    - name: Archive coverage results
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: |
          coverage.xml
          htmlcov/
          coverage.svg

  integration-test:
    runs-on: ubuntu-latest
    needs: test
    continue-on-error: true

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.11

    - name: Create virtual environment and install dependencies
      run: |
        uv sync --all-extras

    - name: Run integration tests
      env:
        PYTHONPATH: .
        FLASK_SECRET: "test-secret-key-for-ci"
        REDIS_URL: "redis://localhost:6379/15"
        RECAPTCHA_PUBLIC_KEY: "test-public-key"
        RECAPTCHA_PRIVATE_KEY: "test-private-key"
        AWS_ACCESS_KEY_ID: "test-access-key"
        AWS_SECRET_ACCESS_KEY: "test-secret-key"
        DISABLE_CAPTCHA: "true"
        DEVELOPMENT: "true"
      run: |
        uv run pytest tests/test_integration.py -m "not selenium" -v || true

  selenium-test:
    runs-on: ubuntu-latest
    needs: test
    continue-on-error: true

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          fontconfig \
          fonts-liberation \
          texlive-base \
          texlive-latex-base \
          texlive-luatex \
          latexmk

    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable

    - name: Create virtual environment and install dependencies
      run: |
        uv sync --group dev

    - name: Build application container
      run: |
        docker compose -f docker-compose-dev.yaml build

    - name: Start application services
      env:
        FLASK_SECRET: "test-secret-key-for-ci"
        REDIS_URL: "redis://localhost:6379/0"
        RECAPTCHA_PUBLIC_KEY: "test-public-key"
        RECAPTCHA_PRIVATE_KEY: "test-private-key"
        AWS_ACCESS_KEY_ID: "test-access-key"
        AWS_SECRET_ACCESS_KEY: "test-secret-key"
        DISABLE_CAPTCHA: "true"
        DEVELOPMENT: "true"
      run: |
        docker compose -f docker-compose-dev.yaml up -d
        # Check status of services (sqlite_db exits after creating the database file, which is expected)
        docker compose -f docker-compose-dev.yaml ps
        # Give services time to start
        sleep 30

    - name: Wait for application to be ready
      run: |
        timeout 60 bash -c 'until curl -s http://localhost:8000/health || curl -s http://localhost:8000; do sleep 2; done'

    - name: Run Selenium tests
      env:
        TEST_APP_URL: "http://localhost:8000"
        PYTHONPATH: .
      run: |
        uv run pytest tests/test_ui_selenium.py -v --tb=short

    - name: Stop application services
      if: always()
      run: |
        docker compose -f docker-compose-dev.yaml logs
        docker compose -f docker-compose-dev.yaml down

  security-scan:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install security tools
      run: |
        uv sync --all-extras

    - name: Run safety check
      run: |
        uv run safety check --json || true

    - name: Run bandit security scan
      run: |
        uv run bandit -r app.py armymarkdown/ db/ login.py forms.py clear-redis.py monitor-celery.py -f json || true
