name: Test Suite

on:
  push:
    branches: [ main, develop, feature/*, devops-improvements ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: true
    
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.11

    - name: Create virtual environment and install dependencies
      run: |
        uv venv
        uv pip install -r requirements.txt
        uv pip install -r requirements-test.txt

    - name: Set up test environment
      run: |
        export FLASK_SECRET="test-secret-key-for-ci"
        export REDIS_URL="redis://localhost:6379/15"
        export RECAPTCHA_PUBLIC_KEY="test-public-key"
        export RECAPTCHA_PRIVATE_KEY="test-private-key"
        export AWS_ACCESS_KEY_ID="test-access-key"
        export AWS_SECRET_ACCESS_KEY="test-secret-key"
        export DISABLE_CAPTCHA="true"
        export DEVELOPMENT="true"

    - name: Run code quality checks
      run: |
        source .venv/bin/activate
        ruff check . --output-format=github
        ruff format --check .

    - name: Run type checking
      run: |
        source .venv/bin/activate
        mypy --ignore-missing-imports armymarkdown/ || true

    - name: Run security checks
      run: |
        source .venv/bin/activate
        bandit -r . -f json || true
        safety check || true

    - name: Run unit tests with coverage
      env:
        PYTHONPATH: .
        FLASK_SECRET: "test-secret-key-for-ci"
        REDIS_URL: "redis://localhost:6379/15"
        RECAPTCHA_PUBLIC_KEY: "test-public-key"
        RECAPTCHA_PRIVATE_KEY: "test-private-key"
        AWS_ACCESS_KEY_ID: "test-access-key"
        AWS_SECRET_ACCESS_KEY: "test-secret-key"
        DISABLE_CAPTCHA: "true"
        DEVELOPMENT: "true"
      run: |
        source .venv/bin/activate
        pytest tests/ --cov=. --cov-report=xml --cov-report=html --cov-report=term-missing --continue-on-collection-errors --forked --tb=short --maxfail=10 -v || true

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Generate coverage badge
      run: |
        source .venv/bin/activate
        coverage-badge -o coverage.svg || true

    - name: Archive coverage results
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: |
          coverage.xml
          htmlcov/
          coverage.svg

  integration-test:
    runs-on: ubuntu-latest
    needs: test
    continue-on-error: true
    
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.11

    - name: Create virtual environment and install dependencies
      run: |
        uv venv
        uv pip install -r requirements.txt
        uv pip install -r requirements-test.txt

    - name: Run integration tests
      env:
        PYTHONPATH: .
        FLASK_SECRET: "test-secret-key-for-ci"
        REDIS_URL: "redis://localhost:6379/15"
        RECAPTCHA_PUBLIC_KEY: "test-public-key"
        RECAPTCHA_PRIVATE_KEY: "test-private-key"
        AWS_ACCESS_KEY_ID: "test-access-key"
        AWS_SECRET_ACCESS_KEY: "test-secret-key"
        DISABLE_CAPTCHA: "true"
        DEVELOPMENT: "true"
      run: |
        source .venv/bin/activate
        pytest tests/test_integration.py -v || true

  security-scan:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.11

    - name: Install security tools
      run: |
        uv venv
        uv pip install safety bandit

    - name: Run safety check
      run: |
        source .venv/bin/activate
        safety check --json || true

    - name: Run bandit security scan
      run: |
        source .venv/bin/activate
        bandit -r . -f json || true